// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("FSharp.Quotations.Evaluator.Hacks.NetStandard")]
[assembly: AssemblyProductAttribute("FSharp.Quotations.Evaluator")]
[assembly: AssemblyDescriptionAttribute("A quotations evaluator for F# based on LINQ expression tree compilation")]
[assembly: AssemblyVersionAttribute("1.0.7")]
[assembly: AssemblyFileVersionAttribute("1.0.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "FSharp.Quotations.Evaluator.Hacks.NetStandard";
        internal const System.String AssemblyProduct = "FSharp.Quotations.Evaluator";
        internal const System.String AssemblyDescription = "A quotations evaluator for F# based on LINQ expression tree compilation";
        internal const System.String AssemblyVersion = "1.0.7";
        internal const System.String AssemblyFileVersion = "1.0.7";
    }
}
